# <span style="color:purple"> Getting started with ndarray

**ndarrays** are time and space-efficient multidimensional arrays at the core of numpy. Like the data structures in week2, let's get started by creating ndarrays, using the numpy package.

## <span style = "color:blue"> How to create Rank 1 numpy arrays:

### Setting the place

In [3]:
import numpy as np

an_array = np.array([3, 33, 333])  # Create a rank 1 array

print(type(an_array))              # The type of an array is: "<class 'numpy.ndarray'> "

<class 'numpy.ndarray'>


In [4]:
# test the shape of the array we just created, it should have just one dimension
print(an_array.shape)

(3,)


In [5]:
# because this is an 1-rank array, we need only one index to access each element
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [8]:
an_array[0] = 888         # ndarrays are mutable, here we change one element
print(an_array)

[888  33 333]


## <span style = "color:blue"> How to create a Rank 2 numpy array:

A rank 2 **ndarray** is one with two dimensions. Notice the format below of [ [row] , [row] ]. 2 dimensional arrays are great for representing matrices wich are often useful in data science.

In [19]:
another = np.array([[11,12,13],[21,22,23]])    # Create a rank 2 array

print(another)    # print the array

print("The shape is 2 rows, 3 columns:", another.shape)    # rows x columns

print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray: ", another[0, 0], ", ", another[0, 1], ", ",  another[1, 0])


[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns: (2, 3)
Accessing elements [0,0], [0,1], and [1,0] of the ndarray:  11 , 12 ,  21


## <span style = "color:blue"> There are many ways to create numpy arrays

Here we create a number of different size arrays with different shapes and different pre-filled values. Numpy has a number of built-in methods which help us quickly and easily create multidimensional arrays.

In [20]:
import numpy as np

# create a 2x2 array of zeros
exp1 = np.zeros((2,2))
print(exp1)

[[0. 0.]
 [0. 0.]]


In [22]:
# create a 2x2 array filled with 9.0
exp2 = np.full((2,2), 9.0)
print(exp2)

[[9. 9.]
 [9. 9.]]


In [26]:
# create a 2x2 matrix with the diagonal 1's and the others 0's.

exp3 = np.eye(2,2)
print(exp3)

[[1. 0.]
 [0. 1.]]


In [28]:
# create an array of ones 
exp4 = np.ones((1,2))
print(exp4)

[[1. 1.]]


In [29]:
# notice that the above ndarray (exp4) is actually rank 2, it is a 1x2 array

print(exp4.shape)

# which means we need to use two indexes to access an element
print()
print(exp4[0,1])

(1, 2)

1.0


In [31]:
# create a 2x2 array of random floats between 0 and 1

exp5 = np.random.random((2,2))
print(exp5)

[[0.99770274 0.68194758]
 [0.87738007 0.32044353]]
